// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer the pooled URL because some local networks cannot reach the
    // Supabase direct IPv6 host. Set PRISMA_CLI_DATABASE_URL to override.
    url: process.env["PRISMA_CLI_DATABASE_URL"] ?? process.env["DATABASE_URL"] ?? process.env["DIRECT_URL"],
  },
});
